///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace GIT_TEST
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the GIT_TESTRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("cc7c0311-87fb-4a25-a831-ad2966a6f1f4")]
    public partial class GIT_TESTRepository : RepoGenBaseFolder
    {
        static GIT_TESTRepository instance = new GIT_TESTRepository();

        /// <summary>
        /// Gets the singleton class instance representing the GIT_TESTRepository element repository.
        /// </summary>
        [RepositoryFolder("cc7c0311-87fb-4a25-a831-ad2966a6f1f4")]
        public static GIT_TESTRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public GIT_TESTRepository() 
            : base("GIT_TESTRepository", "/", null, 0, false, "cc7c0311-87fb-4a25-a831-ad2966a6f1f4", ".\\RepositoryImages\\GIT_TESTRepositorycc7c0311.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("cc7c0311-87fb-4a25-a831-ad2966a6f1f4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class GIT_TESTRepositoryFolders
    {
    }
#pragma warning restore 0436
}
